# Preface {-}

# Introduction {#intro} 

Plunger valves are mainly used where volume flows or pressure have to be reduced and regulated with out vibrations, noises or big changes in the pipeline system.

The following advantages are obtained from the plunger valves [@r.heiler]:

  - universal use wide controllable range;
  - low cavitation coefficient, stable flow, low noise;
  - flow block is variable: optimum flow for every operating conditions;
  - low drive forces with pressure-relieving fix and mobile cylinder (pistons);

Plunger valves are control devices that cause pressure loss in pipeline systems by throttling to throttling to modify the flow or pressure so that the desired values are obtained, depending on the degree of opening adjustment.

To size a control valve, the following points must be considered [@r.heiler]:

  - The control valve must be permit the maximum flow under the lowest-possible differential pressure.
  - The flow range (maximum, median and minimum) relative to the degree of opening of the control valve must be such that the regulation circuit is stable.
  - In the entire control range (maximum, median and minimum), there should be no occurrence of cavitation.
  - The pipeline systems are planned and installed, bearing in mind future requirements, and it is often forgotten that control valves designed for this end capacities are oversized at the start of the operation but not for the future requirements. Reducing the size of the control valve means generating additional problems and costs in the future of system operation.

One of the most uncomfortable things that can a hydraulic design Ingenieur happens is a valve that he/she chose for six months ago deteriorate and having to listen to the unflattering comments made by the maintenance department. The most common causes of premature valve failure are:

  - cavitation damage.
  - cavitation and flashing of water (shock flow).
  - erosion of the valve.
  - vibration, (unstable flow pattern with liquids).
  - corrosion.
  - leakages (valve/actuator may be cycling).

To avoid in any way, the following design criteria must be met [@baumann2009]:

  - Criteria for valve selection :
    - Is the valve appropriately sized? 
    - Does the valve have a low dead band, sometimes confused with hysteresis? 
    - Will it be able to operate without a positioner (also a cost factor)? 
    - Does it have adequate rangeability? 
    - Is the flow characteristic acceptable (installed characteristic)? 
    - How is its dynamic performance (frequency response, time constant)? 

  - Installation and affects on the environment:
    - Is the face-to-face such that it can be replaced with another make? 
    - How heavy is it? 
    - Are supports needed? 
    - Is it too tall?
    - Is it going to be noisy under the given flow conditions? 
    - Is there energy supply (in the case of electric actuators)? 
    - Can it withstand the corrosive effects of fluid and the environment? 
    - Would the valve be cavitating under the given flow conditions? 
    - If outdoors, can the valve and actuator stand extreme weather conditions? 

  - Maintainability and long-term cost:
    - Is it easy to repair? 
    - What are the costs of spare parts? 
    - Can the actuator tolerate a vibrating environment? 
    - How is the actuator protected from corrosion? 
    - Is the packings field-replaceable? 
    - Is the control cylinders (fix and mobile) are field-replaceable? 
    - Is the actuator able to diagnose the valve? 
    
Another essential point to consider is the information available. Sizing the flow to the fifth place after the decimal point is all well and good, but only if you know the right process conditions [@baumann2009]: 

  - First of all, the valve should be sized to control the maximum flow rate under the lowest-possible differential pressure. But what is maximum flow this exactly? 
  - How about emergency conditions? 
  - On the other hand, should the valve fail full open, would the resultant flow be more than the downstream pipe or valve could handle? 
  - what is the correct inlet pressure? 
  - What are the variations in inlet pressure?
  - Can you use the head pressure of the pump from the manufacturer’s published curve? (If you do, use the head pressure corresponding to the maximum flow the valve has to pass, and don’t ignore the static head at the pump’s location.) 
  - How about line losses? 

My experience is that all these questions will be answered in a vague form from the design people. They don’t know either and have to rely on the input from other departments. The result is usually guesswork with ample safety factors thrown in. 

Only after reviewing these criteria and deciding on the proper valve type should the subject of cost be considered

## Structure of the document {-}

This document focuses on the sizing of plunger control valves in the transportation and distribution of drinking and raw water. 

It is recommended that readers have a basic understanding of hydraulic. Part I Theory introduces the fundamental usage and syntax, which should be sufficient to get most readers started in sizing a control valve.  This part provides an overview of the basics hydraulic functions and is recommended reading for any new users of this document. 

In part II praxis, I will concentrate on the development of examples, based on the information published by the different manufacturers of plunger valves. 

Reading these documents does not exclude knowledge of the different European, American, and regional standards regarding control valve sizing. It is also necessary to have access to the norms, technical literature, and information of the producer about control valve sizing to delve into the different concepts.

This document is a compilation of existing information in the European, American standards, books and articles by different authors and articles by different manufacturers of valves. I have tried to cite all of the above sources, but I apologize in advance if this is not correct at any time.

## Normative references {#norms}

The following referenced documents are indispensable for the application of this document. For dated references, only the edition cited applies. For undated references, the latest version of the referenced material (including any amendments) applies.

  - **EN 736-1:1995**, Valves — Terminology — Part 1: Definition of types of valves
  - **EN 736-3:2008**, Valves — Terminology — Part 3: Definition of terms
  - **EN 1057**, Copper and copper alloys — Seamless, round copper tubes for water and gas in sanitary and heating applications
  - **EN 24006:1993**, Measurement of fluid flow in closed conduits — Vocabulary and symbols (ISO 4006:1991)
  - **EN ISO 6708:1995**, Pipework components — Definition and selection of DN (nominal size) (ISO 6708:1995)
  - **ISO 7-1:1994**, Pipe threads where pressure-tight joints are made on the threads — Part 1: Dimensions, tolerances and designation
  - **ISO 7194:2008**, Measurement of fluid flow in closed conduits — Velocity-area methods of flow measurement in swirling or asymmetric flow conditions in circular ducts by means of current-meters or Pitot static tubes

**Other International Normative references**

  - **ISA Guide**     Control Valves, Practical Guides for Measurement and Control.
  - **ISA S20.50**    Specification Forms for Process Measurement and Control Instruments, Primary Elements and Control Valves.
  - **ISA S75.01**    Flow Equations for Sizing Control Valves.
  - **ISA S75.05**    Control Valve Terminology.
  - **ISA S75.11**    Inherent Flow Characteristic and Rangeability of Control Valves.
  - **ISA SP75.17**   Control Valve Aerodynamic Noise Prediction.
  - **ISA RP75.23**   Considerations for Evaluating Control Valve Cavitation.
  - **ANSI/ISA-75.02-1996**, Control Valve Capacity Test Procedures.
  - **ANSI/ISA-75.05.01-2000 (R2005)**, Control Valve Terminology.
  - **IEC 60534-1:2005**, Industrial-process control valves – Part 1: Control valve terminology and general considerations.
  - **IEC 60534-2-3:1997**, Industrial-process control valves – Part 2-3: Flow capacity – Test procedures.


## Nomenclature {#nomenclature}

| Symbol        | Description                                          | Units (notes) |
|:--------------|:-----------------------------------------------------|:--------------|
| $d$           | Valve inlet diameter                                 |mm|
| $D$           | Internal diameter of the pipe                        |mm|
| $F_d$         | Valve style modifier                                 |dimensionless|
| $F_F$         | Liquid critical pressure ratio factor, dimensionless |dimensionless|
| $F_L$         | Liquid pressure recovery factor of a valve without attached fittings|dimensionless|
| $F_{LP}$      | Product of the liquid pressure recovery factor of a valve with attached fittings (no symbol has been identified) and the piping geometry factor|dimensionless|
| $F_P$         | Piping geometry factor, dimensionless                |dimensionless|
| $F_R$         | Reynolds number factor, dimensionless                |dimensionless|
| $K_c$         | coefficient of constant cavitation                   |dimensionless|
| $g$           | Local acceleration of gravity                        |$m^2 / s$|
| $K_v$         | Valve flow coefficient                               |$m^3/h$|
| $p_1$         | Upstream **_absolute_** static pressure, measured two nominal pipe diameters upstream of valve-fitting assembly |$bar$ absolute|
| $p_2$         | Downstream **_absolute_** static pressure, measured six nominal pipe diameters downstream of valve-fitting assembly |$bar$ absolute|
| $P_c$         | Absolute thermodynamic critical pressure             |$bar$ absolute|
| $P_v$         | Absolute vapor pressure of the liquid at inlet temperature |$bar$ absolute|
| $P_{vc}$      | Apparent absolute pressure at vena contracta         |$bar$ absolute|
| $\Delta{P}$   | pressure differential between upstream and downstream pressures $(p_1 - p_2)$ | $bar$|
| $\Delta{P_{max}}$ | maximum allowable pressure differential for control valve sizing purposes for in-compressible fluids | $bar$|
| $q$           | Volumetric flow rate                                 |$m^3/h$|
| $q_{max}$     | Maximum flow rate (choked flow conditions) at a given upstream condition |$m^3/h$|
| $Re_v$        | Valve Reynolds number                                |dimensionless|
| $T_1$         | Upstream temperature (inlet absolute temperature)    |$K$|
| $X$           | ratio of pressure differential to inlet absolute pressure| dimensionless|
| $X_{cr}$      | ratio of pressure differential to inlet absolute pressure in critical conditions $(\Delta{p} / p_1)_{cr}$ | dimensionless |
| $X_{FZ}$      | coefficient of incipient cavitation|dimensionless|
| $\gamma_{1} \; (Gamma)$ | Specific weight, upstream conditions       ||
| $\mu \; (mu)$           | dynamic viscosity, absolute                |$Pa \; s$|
| $\rho_{0} \; (rho)$ | specific mass of water at 15.5 °C i.e. 999 $kg/m^3$   |$kg/m^3$|
| $\rho_{1} \; (rho)$ | specific mass of fluid at $p_1$ and $T_1$  |$kg/m^3$|
| $\rho_{0} / \rho_{1}$ | ratio of specific mass of fluid in upstream condition to specific mass of water at 15.5 °C  |dimensionless|
| $\upsilon$| kinematic viscosity $(\upsilon= \mu / \rho )$|$m^2/s$|
| $\epsilon$ | Surface roughness often shortened to roughness, is a component of surface texture. |$mm$|
| $\epsilon / D$ | The pipe's relative roughness, where ε is the pipe's effective roughness height and D the pipe (inside) diameter. |  dimensionless|
| $f$| stands for the Darcy friction factor. Its value depends on the flow's Reynolds number $Re$ and on the pipe's relative roughness $\epsilon / d$.| dimensionless |











