# Valves Hidraulic {#HydraulicValves}

## The _Flow coefficient_ $k_{v}$ 

Flow factor $k_{v}$  combines the effects of all flow restrictions in the valve into a single number.
$k_{v}$ represents the flow of water with temperature ranging between $5째C$ and $30째C$ through a valve in cubic meters per hour with a pressure drop of $1 bar$ [@wagner2008].

Do you need for the calculation of the valve flow factor ($k_{v}$) : 

 - operating pressure differential; 
 - flow rate for your application; 
 - Density of the fluid; 
 - and in some circumstances, temperature. 

## _Flow coefficient_ $k_{v}$ and _Loss Coefficient_ $\zeta_{v}$ 

The valve flow coefficient $k_v$ is defined as the number of cubic meters per hour of 5째C to 30째C water that will flow through a control valve at a specified position of the control valve (travel) $h$ with a differential pressure ($\Delta p=p_1-p_2$) of 105 Pa (1bar) across it.

The standard conditions referred to in definitions of flow coefficients ($K_v$) are the following:

  - flow in turbulent condition;
  - no cavitation and vaporisation phenomena;
  - valve diameter equal to pipe diameter;
  - static pressure drop measured between upstream and downstream pressure taps;
  - straight pipe lengths upstream and downstream the valve;
  - Newtonian fluid.

According to this European Standard, the flow rate characteristic parameter of a valve is the flow coefficient, $K_v$. The equation, the quantity subject to measurement and input quantities are the following [@wagner2008].

\begin{equation} 
  K_v = q \cdot \sqrt{\frac {(\rho / \rho_{0})}{\Delta P}} 
  (\#eq:Kv-01)
\end{equation} 

 - $\Delta P$ : operating pressure differential; 
 - $q$ : flow rate for your application; 
 - $\rho_{0}$ : Density of Liquids; 
 - $d$ Nominal size 
 - $K_v$: Flow $m^3/hour$ at $\Delta P = 1 \, bar$    
 - and in some circumstances, temperature $T$. 


\begin{equation} 
  K_{v} = q \cdot \sqrt{\frac{1}{\Delta P }} = \frac{q}{\sqrt{\Delta P}}
  (\#eq:Kv-02)
\end{equation} 

 - If the $\zeta$ value of the valve is : 

\begin{equation}
  \zeta_{v} = {\frac{1}{626.3} \cdot  \bigg( {\frac{d^2}{{K_v}}}} \bigg)^2
  (\#eq:zeta-01)
\end{equation} 

  - The $K_{v}$ in function of the $\zeta_{v}$ is:
  
\begin{equation}
  K_v = \frac{d^2}{\sqrt{626.3}} \cdot \frac{1}{\sqrt{\zeta}}
  (\#eq:Kv-03)  
\end{equation} 

## The flow basic characteristic curve (inherent flow characteristic).

The characteristic of a control valve is defined as the flow rate depending on the position of the valve. The control valve generates a change in the flow by changing the active area of piston $A$. 

To perform a required flow characteristic curve, it is necessary to determine the characteristic opening curve that delivers the needed flow rate, taking into account the variable area of the cylinder area, according to the path of the regulating cylinder.

A unique assignment assumes a constant differential pressure $\Delta p$ and a constant density $\rho$.

If the characteristic curve is determined under unit conditions, referred to below as the *"basic characteristic curve"*. The valve characteristic curve is a function of valve position (degree of opening) $vp$ in percentage. 

The characteristic curve of a control valve is the dependence of the flow on the actuating path. If the characteristic curve is determined under unit conditions, then the flow rate is the $k_v$ value. 

The basic characteristic of the control valves plus a cylinder  will be ($K_v/K_{vs}$) depending on the position of the valve ($pv$). For the most precise interpretation in the function, we will use $x = valve \; position$ to define the valve position.

\begin{equation}
  K_v/K_{vs} = f(x, (b, d, e))
  (\#eq:characteristic-curve)  
\end{equation} 

In this document, the characteristic curves are approximated by means of the  Dose-Response Analysis ($dcr$).  Dose-response models are regression models where the independent variable referred to as the dose, or in our case, the opening degree of a valve. In contrast, the dependent variable is generally referred to as response or effect. 

The full specification of a statistical dose-response (regression) model involves specifying how the mean is described by a parametric function of dose (valve position) as well as assumptions about the distribution of the response ($K_v$).

A large number of more or less well-known model functions are building in $drc$.  These models are parameterized using a unified structure with the coefficients: 

  - $b$ denoting the steepness of the dose-response curve, 
  - $c$ (in this case 0) and $d$ the lower and upper asymptotes or limits of the response, and, 
  - for some models, $e$ the effective dose. 

By far the log-logistic models are the most used dose-response models. The four-parameter log-logistic model corresponds to the model function:

\begin{equation}
  f(x, (b, d, e)) =  \frac{d}{1 + \exp( b \cdot (\log{x} - \log{e}))}
  (\#eq:Dose-response-model)  
\end{equation} 

## Zeta value in function of the $K_v/K_{vs}$ characteristic curve

If \@ref(eq:zeta-01) and \@ref(eq:Kv-03) for $K_{vs}$ then:


\begin{equation}
  \zeta_{v} = {\frac{1}{626.3} \cdot  \bigg( {\frac{d^2}{{K_v}}}} \bigg)^2 \: ; \: 
  K_{v} = \frac{d^2}{\sqrt{626.3}} \cdot \frac{1}{\sqrt{\zeta_{v}}}
\end{equation} 

if

\begin{equation}
  K_{v} = f(x, (b, d, e)) \cdot K_{vs} \\ K_{v} = f(x, (b, d, e)) \cdot  \frac{d^2}{\sqrt{626.3}} \cdot     \frac{1}{\sqrt{\zeta_{vs}}}
\end{equation} 

then

\begin{equation}
  \frac{1}{K_{v}^2} = \frac{\zeta_{vs}}{[f(x, (b, d, e))]^2} \cdot \frac{626.3}{d^4} \\
  {\frac{1}{626.3} \cdot  \bigg( {\frac{d^2}{{K_v}}}} \bigg)^2 = \frac{\zeta_{vs}}{[f(vp\%)]^2}
\end{equation} 

then:

\begin{equation}
  \zeta_{v} = \frac{\zeta_{vs}}{[f(x, (b, d, e))]^2}
  (\#eq:zeta-02)
\end{equation} 
