# (PART) Praxis {-} 

# Use of flow rate equations for sizing valves

## Example 1: Sizing a valve with constant flow, constant upstream, and constant downstream pressures.

   - Step 1. Specify the variables required  to size the valve.
   - Step 2. Determine the equation constants.
   - Step 3. Determine the flow coefficient $k_v$, the opening degree for the flow and $F_L$.
   
   - Step 4. Determine the pressure drop to use for sizing ($\Delta{P_{sizing}}).$
   - Step 5. Calculate the required flow coefficient ($K_v$).
   
   

### Step 1. Specify the variables required  to size the valve.

```{r include=FALSE}

  library(tidyverse)
  library(wcontrolvalve)

  temp <- 23.30   # °C
  elev <-  0.00   # m 
  p1   <-  5.70   # bar
  p2   <-  4.80   # bar
  flow <- 795.6   # m3/h
  d    <- 0.250   # m
  D1   <- 0.250   # m (DN Pipe Upstream)
  D2   <- 0.250   # m (DN Pipe Downstream)
  

  # cylinter_type <- "E"
  # kv.b  <- -2.393
  # kv.d	<- 1.389
  # kv.e	<- 67.422
  # zvs	  <- 1.780
  # fl	  <- 0.617
  
  # cylinter_type <- "SZ-40"
  # kv.b	<- -2.755
  # kv.d	<-  1.979
  # kv.e	<- 99.215
  # zvs	  <- 15.830
  # fl	  <-  0.775  
  
  cylinder	<- "SZK-30-20%"
  kv.b      <- -3.893
  kv.d	    <- 1.146
  kv.e      <- 61.038
  zvs	      <- 3.000
  fl	      <- 0.598
  
  
```

Service data : 
  1. Water pressure must be managed from 30 bars to 6 bars.
  2. The control valve has a diameter of `r round(d*1000,0)` mm and is smaller than the diameters of the pipe upstream (`r round(D1*1000,0)` mm) and downstream (`r round(D2*1000,0)` mm)  of the valve.

Service Conditions:

  - Fluid : Water 
  - Water Temperature : `r temp` °C
  - Altitude: `r elev` msal.
  - $P_1 =$ `r p1` bar
  - $P_2 =$ `r p2` bar
  - $q =$ `r flow` $m^3/h$ 
  - Diameter Pipe Upstream $D_1$: `r round(D1*1000,0)` mm  
  - Diameter Pipe Downstream $D_2$: `r round(D2*1000,0)` mm  

Valve Design (first approx.):
  
  - Valve: Plunger Valve **VAG RIKO**
  - Diameter Valve $d$: `r round(d*1000,0)` mm  
  - PN-10
  - Control Element : Cylinder type `r cylinder`
  - Control Characteristic: Equal-Percentage Characteristic

### Step 2. Read the constants of the valve.

  - with the valve 100% open: 
    - Zeta Value $\zeta_{vs}$ : `r zvs`
    - Flow coefficient : $K_{vs}$ : `r round(kv_value(d, zvs),1)` $m^3 / h$
    - liquid pressure recovery factor ${F_{L}}_{s}$ : `r fl`
  - Atmosphere Pressure : `r atm_pressure(masl = elev)` bar
  - Vapor Pressure : `r vapour_pressure(temp)*0.01` bar
  - Kinematic viscosity : `r kinematic_viscosity(temp)` $(m^2/s)*1e-6$

### Step 3. Determine the $k_v$, the openindegree for the flow and $F_L$.

from the equqtion \@ref(eq:Kv-01) :

$$
   K_v = q \cdot \sqrt{\frac {(\rho / \rho_{0})}{\Delta P}}
$$

  - $K_v=$ `r round(kv(p1, p2, flow, temp),1)` $m^3 / h$
  - $K_v / K_{vs}=$ `r round(kv(p1, p2, flow, temp)/kv_value(d, zvs)*100,2)`%
  - Position of the valve: `r round(inv_LL3(kv(p1, p2, flow, temp)/kv_value(d, zvs), kv.b, kv.d, kv.e),2)`%
  - $F_L=$ 


### Step 4. Determine the pressure drop to use for sizing ($\Delta{P_{sizing}}).$

